hh/src/main/java/edu/avans/hartigehap/domain/Bill.java
package edu.avans.hartigehap.domain;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.Iterator;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * 
 * @author Erco
 */
@Entity
// optional
@Table(name = "BILLS")
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "@id")
@Getter
@Setter
@ToString(callSuper = true, includeFieldNames = true, of = { "billStatus", "currentOrder", "orders" })
public class Bill extends DomainObject {
    private static final long serialVersionUID = 1L;

    public enum BillStatus {
        CREATED, SUBMITTED, PAID
    }

    // represented in database as integer
    @Enumerated(EnumType.ORDINAL)
    private BillStatus billStatus;

    @Temporal(TemporalType.TIMESTAMP)
    private Date submittedTime;

    @Temporal(TemporalType.TIMESTAMP)
    private Date paidTime;

    // unidirectional one-to-one relationship
    @OneToOne(cascade = javax.persistence.CascadeType.ALL)
    private Order currentOrder;

    @OneToMany(cascade = javax.persistence.CascadeType.ALL, mappedBy = "bill")
    private Collection<Order> orders = new ArrayList<Order>();

    // bidirectional one-to-many relationship
    @ManyToOne()
    private DiningTable diningTable;

    // bidirectional one-to-many relationship
    @ManyToOne(cascade = javax.persistence.CascadeType.ALL)
    private Customer customer;

    public Bill() {
        billStatus = BillStatus.CREATED;
        currentOrder = new Order();
        currentOrder.setBill(this);
        orders.add(currentOrder);
    }

    /* business logic */

    @Transient
    public Collection<Order> getSubmittedOrders() {
        Collection<Order> submittedOrders = new ArrayList<Order>();
        Iterator<Order> orderIterator = orders.iterator();
        while (orderIterator.hasNext()) {
            Order tmp = orderIterator.next();
            if (tmp.isSubmittedOrSuccessiveState()) {
                submittedOrders.add(tmp);
            }
        }
        return submittedOrders;
    }

    /**
     * price of *all* orders, so submitted orders and current (not yet
     * submitted) order
     * 
     * @return
     */
    @Transient
    public int getPriceAllOrders() {
        int price = 0;
        Iterator<Order> orderIterator = orders.iterator();
        while (orderIterator.hasNext()) {
            price += orderIterator.next().getPrice();
        }
        return price;
    }

    /**
     * price of the *submitted or successive state* orders only
     * 
     * @return
     */
    @Transient
    public int getPriceSubmittedOrSuccessiveStateOrders() {
        int price = 0;
        Iterator<Order> orderIterator = orders.iterator();
        while (orderIterator.hasNext()) {
            Order tmp = orderIterator.next();
            if (tmp.isSubmittedOrSuccessiveState()) {
                price += tmp.getPrice();
            }
        }
        return price;
    }

    public void submitOrder() throws StateException {
        currentOrder.submit();
        currentOrder = new Order();
        currentOrder.setBill(this);
        orders.add(currentOrder);
    }

    /*
     * as the table gets a new bill, there is no risk that a customer keeps
     * ordering on the submitted or paid bill
     */
    public void submit() throws StateException, EmptyBillException {
        boolean allEmpty = true;
        Iterator<Order> orderIterator = orders.iterator();
        while (orderIterator.hasNext()) {
            Order order = orderIterator.next();
            if (!order.isEmpty()) {
                allEmpty = false;
                break;
            }
        }
        if (allEmpty) {
            throw new EmptyBillException("not allowed to submit an empty bill");
        }

        if (!currentOrder.isEmpty() && currentOrder.getOrderStatus() == Order.OrderStatus.CREATED) {
            // the currentOrder is not empty, but not yet submitted
            throw new StateException("not allowed to submit an with currentOrder in created state");
        }

        // this can only happen by directly invoking HTTP requests, so not via
        // GUI
        // TODO better to use another exception, because now GUI shows wrong
        // error message
        if (billStatus != BillStatus.CREATED) {
            throw new StateException("not allowed to submit an already submitted bill");
        }

        submittedTime = new Date();
        billStatus = BillStatus.SUBMITTED;
    }

    @Transient
    public boolean isSubmitted() {
        return billStatus == BillStatus.SUBMITTED;
    }

    public void paid() throws StateException {

        // this can only happen by directly invoking HTTP requests, so not via
        // GUI
        if (billStatus != BillStatus.SUBMITTED) {
            throw new StateException("not allowed to pay an bill that is not in the submitted state");
        }

        paidTime = new Date();
        billStatus = BillStatus.PAID;
    }

}

hh/src/main/java/edu/avans/hartigehap/domain/ConcreteOrderItem.java
package edu.avans.hartigehap.domain;

import javax.persistence.Entity;

import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
public class ConcreteOrderItem extends OrderItem{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

}

hh/src/main/java/edu/avans/hartigehap/domain/Customer.java
package edu.avans.hartigehap.domain;

import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Lob;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.NotEmpty;
import org.joda.time.DateTime;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;


/**
 * 
 * @author Erco
 */
@Entity
@Table(name = "CUSTOMERS")
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "@id")
@Getter
@Setter
@ToString(callSuper = true, includeFieldNames = true, of = { "firstName", "lastName", "bills" })
@NoArgsConstructor
public class Customer extends DomainObject {
    private static final long serialVersionUID = 1L;

    @NotEmpty(message = "{validation.firstname.NotEmpty.message}")
    @Size(min = 3, max = 60, message = "{validation.firstname.Size.message}")
    private String firstName;

    @NotEmpty(message = "{validation.lastname.NotEmpty.message}")
    @Size(min = 1, max = 40, message = "{validation.lastname.Size.message}")
    private String lastName;

    // works with hibernate 3.x
    // @Type(type="org.joda.time.contrib.hibernate.PersistentDateTime")
    // to allow using Joda's DateTime with hibernate 4.x use:
    @Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime")
    // needed to allow changing a date in the GUI
    @DateTimeFormat(iso = ISO.DATE)
    private DateTime birthDate;

    private int partySize;

    private String description;

    @Basic(fetch = FetchType.LAZY)
    @Lob
    @Column(name = "PHOTO")
    private byte[] photo;

    // no cascading
    @ManyToMany
    private Collection<Restaurant> restaurants = new ArrayList<Restaurant>();

    // no cascading
    // bidirectional one-to-many; mapping on the database happens at the many
    // side
    @OneToMany(mappedBy = "customer")
    private Collection<Bill> bills = new ArrayList<Bill>();

    // TODO not complete (bills)
    public Customer(String firstName, String lastName, DateTime birthDate, int partySize, String description,
            byte[] photo) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.birthDate = birthDate;
        this.partySize = partySize;
        this.description = description;
        this.photo = photo.clone();
    }

    // This method only updates user-editable fields
    // id, version, restaurants, bills are considered not user-editable
    public void updateEditableFields(Customer customer) {
        firstName = customer.firstName;
        lastName = customer.lastName;
        birthDate = customer.birthDate;
        description = customer.description;
        // hack
        // the "if" is a hack
        // when you change a customer without changing the photo, the customer
        // object passed to the server by editcustomer has the non-changed fields
        // filled in, except for the photo.
        // result is that changing only one field of a customer effectively deletes the photo
        // hack: only update the photo when a new photo is passed
        // downside of this hack: it is not possible any more to delete the photo
        if(customer.photo.length != 0) {
            photo = customer.photo;
        }
        partySize = customer.partySize;
    }

    // example of a "derived property". This property can be be easily derived
    // from the property "birthDate", so no need to persist it.
    @Transient
    public String getBirthDateString() {
        String birthDateString = "";
        if (birthDate != null) {
            birthDateString = org.joda.time.format.DateTimeFormat.forPattern("yyyy-MM-dd").print(birthDate);
        }
        return birthDateString;
    }

    // business logic

}

hh/src/main/java/edu/avans/hartigehap/domain/DecoratedOrderItem.java
package edu.avans.hartigehap.domain;

import javax.persistence.Entity;

import javax.persistence.OneToOne;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

//@Entity


@ToString(callSuper=true, includeFieldNames=true)

@Getter @Setter


@NoArgsConstructor

public abstract class DecoratedOrderItem extends OrderItem {
	private static final long serialVersionUID = 1L;
	
	@OneToOne
	private OrderItem orderItem;
	private int quantity;

	public DecoratedOrderItem(OrderItem toBeDecoratedOrderItem, MenuItem menuItem, int quantity){
		super(menuItem, quantity);
		orderItem = toBeDecoratedOrderItem;
		this.quantity = quantity;
	}
	
	public String description(){
		
		return "decorated order";	
	}
	
	@Transient
	public int getPrice(){
		
		return orderItem.getPrice();
		
	}
	
	
	
	

}

hh/src/main/java/edu/avans/hartigehap/domain/DiningTable.java
package edu.avans.hartigehap.domain;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * 
 * @author Erco
 */
@Entity
@Table(name = "DININGTABLES")
// optional
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "@id")
@Getter
@Setter
@ToString(callSuper = true, includeFieldNames = true, of = { "bills", "currentBill" })
public class DiningTable extends DomainObject {
    private static final long serialVersionUID = 1L;

    private int tableNr;

    // example of an *unidirectional* one-to-one relationship, mapped on
    // database by diningTable side
    @OneToOne(cascade = javax.persistence.CascadeType.ALL)
    private Bill currentBill;

    @OneToMany(cascade = javax.persistence.CascadeType.ALL, mappedBy = "diningTable")
    private Collection<Bill> bills = new ArrayList<Bill>();

    @ManyToOne()
    private Restaurant restaurant;

    public DiningTable() {
        // when the system resets, the c'tor is executed and a new Bill object
        // is created (which in its turn creates a new order object. However,
        // when the dining table becomes managed, the currentBill as was
        // stored in the database is retrieved, and the new Bill and new Order
        // object, which were not managed yet are discarded.
        currentBill = new Bill();
        currentBill.setDiningTable(this);
        bills.add(currentBill);
    }

    public DiningTable(int tableNr) {
        this.tableNr = tableNr;
        // when the system resets, the c'tor is executed and a new Bill object
        // is created (which in its turn creates a new order object. However,
        // when the dining table becomes managed, the currentBill as was
        // stored in the database is retrieved, and the new Bill and new Order
        // object, which were not managed yet are discarded.
        currentBill = new Bill();
        currentBill.setDiningTable(this);
        bills.add(currentBill);
    }

    /* business logic */

    public void warmup() {
        Iterator<OrderItem> orderItemIterator = currentBill.getCurrentOrder().getOrderItems().iterator();
        while (orderItemIterator.hasNext()) {
            orderItemIterator.next().getId();
            // note: menu items have been warmed up via the restaurant->menu
            // relation; therefore it
            // is not needed to warm these objects via this relation
        }
    }

    public void submitBill() throws StateException, EmptyBillException {
        currentBill.submit();
        currentBill = new Bill();
        currentBill.setDiningTable(this);
        bills.add(currentBill);
    }

}

hh/src/main/java/edu/avans/hartigehap/domain/DomainObject.java
package edu.avans.hartigehap.domain;

import java.io.Serializable;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.Version;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

@MappedSuperclass
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "@id")
@Getter
@Setter
@ToString(includeFieldNames = true, of = { "id", "version" })
public abstract class DomainObject implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Version
    @Setter(AccessLevel.NONE)
    Long version;

    /*
     * This hashCode() implementation violates an important property: - The id
     * changes during the lifetime of the object: before being persisted, the id
     * is not set (so null). During invocation of the persist method, the id is
     * provided by the ORM provider. After being persisted, the id is immutable
     * (as a good id is being supposed to behave). - The result of this
     * violation is that if the entities are used as keys in a HashSet or
     * HashMap, they will become lost when being persisted.
     * 
     * This is the equals() implementation taken from
     * http://www.onjava.com/pub/a
     * /onjava/2006/09/13/dont-let-hibernate-steal-your-identity.html?page=1
     * (see Netbeans project EqualsHashCodeTryOut).
     */
    @Override
    public int hashCode() {
        if (id != null) {
            return id.hashCode();
        } else {
            return super.hashCode();
        }
    }

    /*
     * This equals() implementation is meant for entities with *surrogate id*,
     * where the id is provided by the ORM provider upon invocation of the
     * persist method. This means that there is a period between object creation
     * and persisting of the entity, where the id is not set and therefore null.
     * 
     * The properties are as follows: - if two non-persisted entities are
     * compared, they are by definition unequal. This allow storing them in a
     * set, even before being persisted. - if two persisted entities are
     * compared, they are compared based on their surrogate id (no other
     * information from the object is used). - if a persisted an a non-persisted
     * entity are compared, they are by definition unequal.
     * 
     * This is the equals() implementation taken from
     * http://www.onjava.com/pub/a
     * /onjava/2006/09/13/dont-let-hibernate-steal-your-identity.html?page=1
     * (see Netbeans project EqualsHashCodeTryOut).
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        // null is not an instance of anything, so check whether null is not
        // necessary
        if (!(o instanceof DomainObject)) {
            return false;
        }

        DomainObject other = (DomainObject) o;

        // unsaved objects are never equal
        if (id == null || other.getId() == null) {
            return false;
        }

        return id.equals(other.getId());
    }
}

hh/src/main/webapp/WEB-INF/views/hartigehap/diningtable.jspx
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<div id="body" xmlns:jsp="http://java.sun.com/JSP/Page"
	 xmlns:c="http://java.sun.com/jsp/jstl/core"
	 xmlns:joda="http://www.joda.org/joda/time/tags"
	 xmlns:spring="http://www.springframework.org/tags"
	 xmlns:form="http://www.springframework.org/tags/form"
	 xmlns:sec="http://www.springframework.org/security/tags" version="2.0">
	<jsp:directive.page contentType="text/html;charset=UTF-8" />
	<jsp:output omit-xml-declaration="yes" />

	<spring:message code="label_dining_menu" var="labelDiningMenu" />
	<spring:message code="label_restaurant" var="labelRestaurant" />
	<spring:message code="label_current_order" var="labelCurrentOrder" />
	<spring:message code="label_submit_order_button" var="labelSubmitOrderButton" />
	<spring:message code="label_current_bill" var="labelCurrentBill" />
	<spring:message code="label_submit_bill_button" var="labelSubmitBillButton" />
	<spring:message code="label_price_current_order" var="labelPriceCurrentOrder" />
	<spring:message code="label_total_price_prev_orders" var="labelTotalPricePrevOrders" />
	<spring:message code="label_menu_item" var="labelMenuItem" />
	<spring:message code="label_food_category" var="labelFoodCategory" />
	<spring:message code="label_price" var="labelPrice" />
	<spring:message code="label_add_button" var="labelAddButton" />
	<spring:message code="label_remove_button" var="labelRemoveButton" />
	<spring:message code="label_currency" var="labelCurrency" />
	<spring:message code="label_menu" var="labelMenu" />
	<spring:message code="label_categorie" var="labelCategorie" />
	<spring:message code="label_categorie_tab_text" var="labelCategorieTabText" />
	<spring:message code="label_welcome_word" var="labelWelcomeWord" />
	<spring:message code="label_pick_from_menu" var="labelPickFromMenu" />
	<spring:message code="table_item" var="tableItem" />
	<spring:message code="table_image" var="tableImage" />
	<spring:message code="table_price" var="tablePrice" />
	<spring:message code="table_actions" var="tableActions" />
	<spring:message code="table_quantity" var="tableQuantity" />
	<spring:url var="showRestaurant" value="/restaurants/${restaurant.id}" />

	<div class="row">
		<h1>${labelDiningMenu} ${diningTable.tableNr}</h1>
		<h2 class="restaurant muted">${labelRestaurant} <a href="${showRestaurant}">${restaurant.id}</a></h2>

		<c:if test="${not empty message}">
			<div id="message" class="alert alert-info ${message.type}">${message.message}</div>
		</c:if>
	</div>

	<c:if test="${empty diningTable.currentBill.currentOrder.orderItems}">
		<div class="row">
			<div class="panel panel-default">
				<div class="panel-heading">${labelWelcomeWord}</div>
				<div class="panel-body">
					${labelPickFromMenu}
				</div>
			</div>
		</div>
	</c:if>

	<c:if test="${not empty diningTable.currentBill.currentOrder.orderItems}">
		<div class="row">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">${labelCurrentOrder}</h3>
					<span class="pull-right">
						<!-- Tabs -->
						<ul class="nav panel-tabs">
							<li>
								<spring:url var="submitOrderUrl" value="/diningTables/${diningTable.id}" />
								<form:form name="submitOrderForm" action="${submitOrderUrl}" method="put">
									<input type="hidden" name="event" value="submitOrder" />
									<button type="submit" class="btn btn-default">${labelSubmitOrderButton}</button>
								</form:form>
							</li>
						</ul>
					</span>
				</div>
				<div class="tab-content">
					<table class="table">
						<thead>
							<tr>
								<th>${tableItem}</th>
								<th>${tableQuantity}</th>
							</tr>
						</thead>
						<tbody>
							<c:forEach items="${diningTable.currentBill.currentOrder.orderItems}" var="orderItem">
								<tr>
									<td class="capitalise">${orderItem.menuItem.id}</td>
									<td>${orderItem.quantity}</td>
								</tr>
							</c:forEach>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</c:if>

	<c:if test="${diningTable.currentBill.priceSubmittedOrSuccessiveStateOrders ne '0'}">
		<div class="row">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">${labelCurrentBill}</h3>
					<span class="pull-right">
						<!-- Tabs -->
						<ul class="nav panel-tabs">
							<li>
								<spring:url var="submitBillUrl" value="/diningTables/${diningTable.id}" />
								<form:form name="submitBillForm" action="${submitBillUrl}" method="put">
									<input type="hidden" name="event" value="submitBill" />
									<button type="submit" class="btn btn-success">${labelSubmitBillButton}</button>
								</form:form>
							</li>
						</ul>
					</span>
				</div>
				<div class="tab-content">
					<table class="table">
						<thead>
							<tr>
								<th>${labelPriceCurrentOrder}</th>
								<th>${labelTotalPricePrevOrders}</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>${labelCurrency} ${diningTable.currentBill.currentOrder.price}</td>
								<td>${labelCurrency} ${diningTable.currentBill.priceSubmittedOrSuccessiveStateOrders}</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</c:if>

	<!--
		Show order system with food categories
	-->
	<div class="row">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">${labelMenu}</h3>
				<span class="pull-right">
					<ul class="nav panel-tabs">
						<li class="active"><a href="#tab1" data-toggle="tab" class="capitalise">${labelCategorie}</a></li>
						<c:forEach items="${restaurant.menu.foodCategories}" var="foodCategory">
							<c:if test="${not empty foodCategory.menuItems}">
								<li><a href="#tabs-${foodCategory.id}" class="capitalise" data-toggle="tab">${foodCategory.tag}</a></li>
							</c:if>
						</c:forEach>
					</ul>
				</span>
			</div>
			<div class="tab-content">
				<div class="tab-pane active" id="tab1">
					<div class="panel-body">${labelCategorieTabText}</div>
				</div>
				<c:forEach items="${restaurant.menu.foodCategories}" var="foodCategory">
					<div class="tab-pane" id="tabs-${foodCategory.id}">
						<table class="table">
							<thead>
								<tr>
									<th>${tableItem}</th>
									<th>${tableImage}</th>
									<th>${tablePrice}</th>
									<th>${tableActions}</th>
								</tr>
							</thead>
							<tbody>
								<c:if test="${not empty foodCategory.menuItems}">
									<c:forEach items="${foodCategory.menuItems}" var="menuItem">
										<spring:url var="imageUrl" value="/resources/images/${menuItem.imageFileName}" />
										<tr>
											<td class="capitalise">${menuItem.id}</td>
											<td><img id="menuitemimg" src="${imageUrl}" width="150px" /></td>
											<td>${labelCurrency} ${menuItem.price}</td>
											<td>
												<spring:url var="addOrderItemUrl" value="/diningTables/${diningTable.id}/menuItems" />
												<form:form name="addOrderItemForm" action="${addOrderItemUrl}" method="post">
													<input type="hidden" name="menuItemName" value="${menuItem.id}" />
													<button type="submit" class="btn btn-success btn-float-left-margin-right" value="${labelAddButton}"><span class="glyphicon glyphicon-plus-sign glyphicon-padding-right"><jsp:text /></span> ${labelAddButton}</button>
												</form:form>
												<spring:url var="deleteOrderItemUrl" value="/diningTables/${diningTable.id}/menuItems/${menuItem.id}" />
												<form:form name="deleteOrderItemForm" action="${deleteOrderItemUrl}" method="delete">
													<button type="submit" class="btn btn-danger btn-float-left-margin-right" value="${labelRemoveButton}"><span class="glyphicon glyphicon-remove-sign glyphicon-padding-right"><jsp:text /></span> ${labelRemoveButton}</button>
												</form:form>
											</td>
										</tr>
									</c:forEach>
								</c:if>
							</tbody>
						</table>
					</div>
				</c:forEach>
			</div>
		</div>
	</div>
</div>